#!/bin/bash
# Transforming DTI atlas into native space 
# MB NB EV JM KH January 2026 

# Check script arguments
args=2
usage() {
    COMMAND=$(basename $0)
    echo
    echo "Usage:"
    echo "./$COMMAND [session name] [subject_id]"
    echo
	echo "Example:"
	echo "./$COMMAND ses-02y sub-146"
echo
exit
}
[ $# -ne $args ] && { usage; exit; }

module load mrtrix3/3.0.8

# Set variables and paths
SES=$1
SUBJECT=$2

CURR_DIR=$(pwd)
ROOT_DIR="${CURR_DIR%/*/*}"
DATA_DIR="${ROOT_DIR}/data_derivs/derivatives"
ATLAS_DIR="${ROOT_DIR}/data_derivs/atlases"

DTI_DIR="${DATA_DIR}/DTI/${SUBJECT}/${SES}/dwi"
FMRI_DIR="${DATA_DIR}/fMRI/${SUBJECT}/${SES}/func"
ROI_DIR="${DATA_DIR}/ROIs"


# Make results directory
RESULTS_DIR=${ROOT_DIR}/results/${SUBJECT}
WARP_DIR=${RESULTS_DIR}/warps


# Verify registration
mrview ${OUTPUT_DIR}/atlas_fa.mif \
    -overlay.load ${OUTPUT_DIR}/subject_fa.mif \
    -overlay.opacity 0.5